This is makeindex.exe, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file C:/Users/Nuw_Resh/Desktop/Nuwanpriya_Thesis/Thesis Template/main_thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file main_thesis.acn....done (10 entries accepted, 0 rejected).
Sorting entries....done (35 comparisons).
Generating output file main_thesis.acr....done (29 lines written, 0 warnings).
Output written in main_thesis.acr.
Transcript written in main_thesis.alg.
